say upper("hello world");
say lower("HELLO WORLD");
say upper("Already Mixed 123!");
say trim("   hi there   ");
say trim("no spaces");
say trim("   ");
say substring("hello world", 0, 5);
say substring("hello world", 6, 11);
say substring("hello world", -3, 100);
say substring("hello world", 8, 3);
say indexOf("hello world", "world");
say indexOf("hello world", "xyz");
say indexOf("hello world", "");
say indexOf("hello world", "hello world");
