// Vulkan compute dispatch for the one kernel this backend has so far.
// Same "compiles against the real SDK, never run end-to-end" caveat as
// context.cpp -- this sandbox has no device to dispatch work to at all.
// Most VkResult checks below are omitted (matching this project's
// existing style of not writing defensive code for failures that need
// a debugging session, not a guard, to actually diagnose) -- when this
// runs for the first time on real hardware and something's wrong, run
// it with VK_LAYER_KHRONOS_validation enabled (`vulkan-validation-layers`,
// not installed by install_deps.sh since it's a debug tool, not a build
// dependency); the validation layer will name the exact call and the
// exact violated rule far more precisely than a hand-checked VkResult
// ever would.
#include "H/backends/vulkan/context.h"
#include "H/backends/vulkan/context_internal.hpp"
#include <vulkan/vulkan.h>
#include <cstring>
#include <cstdint>

// Generated by `make` from src/shaders/matrix_multiply.comp via glslc
// -mfmt=c (see Makefile) -- not checked in, same as any other object
// code: `static const uint32_t matrix_multiply_spv[] = {...};`.
#include "H/backends/vulkan/matrix_multiply_spv.h"

namespace {

uint32_t find_memory_type(VkPhysicalDevice phys, uint32_t type_filter, VkMemoryPropertyFlags props) {
    VkPhysicalDeviceMemoryProperties mem_props;
    vkGetPhysicalDeviceMemoryProperties(phys, &mem_props);
    for (uint32_t i = 0; i < mem_props.memoryTypeCount; i++) {
        if ((type_filter & (1u << i)) && (mem_props.memoryTypes[i].propertyFlags & props) == props) return i;
    }
    return UINT32_MAX;
}

struct Buffer {
    VkBuffer buffer = VK_NULL_HANDLE;
    VkDeviceMemory memory = VK_NULL_HANDLE;
    void *mapped = nullptr;
};

// Host-visible + host-coherent memory for every buffer, no staging
// buffer / device-local copy: simplest correct option, not the fastest
// one. A device-local buffer plus an explicit transfer would avoid
// paying PCIe-mapped-memory access cost on every shader read/write, but
// tuning that tradeoff needs a real device to measure against -- there
// isn't one here (see context.cpp).
bool create_host_visible_buffer(VkDevice device, VkPhysicalDevice phys, VkDeviceSize size, Buffer *out) {
    VkBufferCreateInfo buf_info{};
    buf_info.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    buf_info.size = size;
    buf_info.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    buf_info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(device, &buf_info, nullptr, &out->buffer) != VK_SUCCESS) return false;

    VkMemoryRequirements mem_req;
    vkGetBufferMemoryRequirements(device, out->buffer, &mem_req);
    uint32_t mem_type = find_memory_type(phys, mem_req.memoryTypeBits,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (mem_type == UINT32_MAX) return false;

    VkMemoryAllocateInfo alloc_info{};
    alloc_info.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    alloc_info.allocationSize = mem_req.size;
    alloc_info.memoryTypeIndex = mem_type;
    if (vkAllocateMemory(device, &alloc_info, nullptr, &out->memory) != VK_SUCCESS) return false;
    if (vkBindBufferMemory(device, out->buffer, out->memory, 0) != VK_SUCCESS) return false;
    if (vkMapMemory(device, out->memory, 0, size, 0, &out->mapped) != VK_SUCCESS) return false;
    return true;
}

void destroy_buffer(VkDevice device, Buffer &buf) {
    if (buf.mapped) vkUnmapMemory(device, buf.memory);
    if (buf.buffer != VK_NULL_HANDLE) vkDestroyBuffer(device, buf.buffer, nullptr);
    if (buf.memory != VK_NULL_HANDLE) vkFreeMemory(device, buf.memory, nullptr);
    buf = Buffer{};
}

} // namespace

extern "C" void ash_gpu_vulkan_matrix_multiply(const double *a, const double *b, double *c, int n) {
    const AshGpuVulkanContext &ctx = ash_gpu_vulkan_context();
    VkDevice device = ctx.device;
    VkDeviceSize bytes = (VkDeviceSize)n * (VkDeviceSize)n * sizeof(double);

    Buffer buf_a{}, buf_b{}, buf_c{};
    bool ok = create_host_visible_buffer(device, ctx.physical_device, bytes, &buf_a) &&
              create_host_visible_buffer(device, ctx.physical_device, bytes, &buf_b) &&
              create_host_visible_buffer(device, ctx.physical_device, bytes, &buf_c);
    if (!ok) {
        // Caller (runtime/device.c's dispatcher) only reaches this path
        // after ash_gpu_vulkan_init() already succeeded, so this would
        // mean running out of device memory mid-call -- nothing graceful
        // to fall back to from here (the CPU path needs the caller's
        // buffers, which are untouched, so the caller COULD retry on
        // CPU, but this function's contract is "fill C", not "report
        // failure"; see todo.md for making this a real error path).
        destroy_buffer(device, buf_a);
        destroy_buffer(device, buf_b);
        destroy_buffer(device, buf_c);
        return;
    }

    memcpy(buf_a.mapped, a, (size_t)bytes);
    memcpy(buf_b.mapped, b, (size_t)bytes);

    VkDescriptorSetLayoutBinding bindings[3] = {};
    for (int i = 0; i < 3; i++) {
        bindings[i].binding = (uint32_t)i;
        bindings[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bindings[i].descriptorCount = 1;
        bindings[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo layout_info{};
    layout_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    layout_info.bindingCount = 3;
    layout_info.pBindings = bindings;
    VkDescriptorSetLayout set_layout = VK_NULL_HANDLE;
    vkCreateDescriptorSetLayout(device, &layout_info, nullptr, &set_layout);

    VkPushConstantRange push_range{};
    push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    push_range.offset = 0;
    push_range.size = sizeof(uint32_t);

    VkPipelineLayoutCreateInfo pipeline_layout_info{};
    pipeline_layout_info.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    pipeline_layout_info.setLayoutCount = 1;
    pipeline_layout_info.pSetLayouts = &set_layout;
    pipeline_layout_info.pushConstantRangeCount = 1;
    pipeline_layout_info.pPushConstantRanges = &push_range;
    VkPipelineLayout pipeline_layout = VK_NULL_HANDLE;
    vkCreatePipelineLayout(device, &pipeline_layout_info, nullptr, &pipeline_layout);

    VkShaderModuleCreateInfo shader_info{};
    shader_info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    shader_info.codeSize = sizeof(matrix_multiply_spv);
    shader_info.pCode = matrix_multiply_spv;
    VkShaderModule shader_module = VK_NULL_HANDLE;
    vkCreateShaderModule(device, &shader_info, nullptr, &shader_module);

    VkComputePipelineCreateInfo pipeline_info{};
    pipeline_info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    pipeline_info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    pipeline_info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    pipeline_info.stage.module = shader_module;
    pipeline_info.stage.pName = "main";
    pipeline_info.layout = pipeline_layout;
    VkPipeline pipeline = VK_NULL_HANDLE;
    vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &pipeline_info, nullptr, &pipeline);

    VkDescriptorPoolSize pool_size{};
    pool_size.type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    pool_size.descriptorCount = 3;
    VkDescriptorPoolCreateInfo pool_info{};
    pool_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    pool_info.maxSets = 1;
    pool_info.poolSizeCount = 1;
    pool_info.pPoolSizes = &pool_size;
    VkDescriptorPool desc_pool = VK_NULL_HANDLE;
    vkCreateDescriptorPool(device, &pool_info, nullptr, &desc_pool);

    VkDescriptorSetAllocateInfo set_alloc_info{};
    set_alloc_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    set_alloc_info.descriptorPool = desc_pool;
    set_alloc_info.descriptorSetCount = 1;
    set_alloc_info.pSetLayouts = &set_layout;
    VkDescriptorSet desc_set = VK_NULL_HANDLE;
    vkAllocateDescriptorSets(device, &set_alloc_info, &desc_set);

    VkDescriptorBufferInfo buf_infos[3] = {
        {buf_a.buffer, 0, bytes},
        {buf_b.buffer, 0, bytes},
        {buf_c.buffer, 0, bytes},
    };
    VkWriteDescriptorSet writes[3] = {};
    for (int i = 0; i < 3; i++) {
        writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[i].dstSet = desc_set;
        writes[i].dstBinding = (uint32_t)i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[i].pBufferInfo = &buf_infos[i];
    }
    vkUpdateDescriptorSets(device, 3, writes, 0, nullptr);

    VkCommandBufferAllocateInfo cmd_alloc_info{};
    cmd_alloc_info.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    cmd_alloc_info.commandPool = ctx.command_pool;
    cmd_alloc_info.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cmd_alloc_info.commandBufferCount = 1;
    VkCommandBuffer cmd = VK_NULL_HANDLE;
    vkAllocateCommandBuffers(device, &cmd_alloc_info, &cmd);

    VkCommandBufferBeginInfo begin_info{};
    begin_info.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    begin_info.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &begin_info);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_layout, 0, 1, &desc_set, 0, nullptr);
    uint32_t n_u32 = (uint32_t)n;
    vkCmdPushConstants(cmd, pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(uint32_t), &n_u32);
    uint32_t groups = ((uint32_t)n + 15u) / 16u; // matches local_size_x/y = 16 in the shader
    vkCmdDispatch(cmd, groups, groups, 1);
    vkEndCommandBuffer(cmd);

    VkSubmitInfo submit_info{};
    submit_info.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submit_info.commandBufferCount = 1;
    submit_info.pCommandBuffers = &cmd;
    vkQueueSubmit(ctx.compute_queue, 1, &submit_info, VK_NULL_HANDLE);
    vkQueueWaitIdle(ctx.compute_queue); // simplest correct sync: block until done, no overlap with other work

    memcpy(c, buf_c.mapped, (size_t)bytes);

    vkFreeCommandBuffers(device, ctx.command_pool, 1, &cmd);
    vkDestroyDescriptorPool(device, desc_pool, nullptr);
    vkDestroyPipeline(device, pipeline, nullptr);
    vkDestroyShaderModule(device, shader_module, nullptr);
    vkDestroyPipelineLayout(device, pipeline_layout, nullptr);
    vkDestroyDescriptorSetLayout(device, set_layout, nullptr);
    destroy_buffer(device, buf_a);
    destroy_buffer(device, buf_b);
    destroy_buffer(device, buf_c);
}
